
const REFRESH_MAX_AGE = 60*24*60*60*1000
const REFRESH_EXPIRESIN = '60d'
const ACCESS_MAX_AGE = 1000*60*15
const ACCESS_EXPIRESIN = '15m'
const ADMIN_REFRESH_MAX_AGE = 1000*60*60*2
const ADMIN_REFRESH_EXPIRESIN= '2h'

module.exports = {REFRESH_MAX_AGE, REFRESH_EXPIRESIN, ACCESS_EXPIRESIN, ACCESS_MAX_AGE, ADMIN_REFRESH_EXPIRESIN, ADMIN_REFRESH_MAX_AGE}